// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvyvqgtwlwbaurcooypk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2eXZxZ3R3bHdiYXVyY29veXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDY0MjYsImV4cCI6MjA2NjMyMjQyNn0.U72JYxP3gJdgdEJCiywapQVCODq3JH8sn9s5qP77754";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});